## YAML Template.


services:
    elendev.checkout.service_provider:
        class: GenCheckoutBundle\CheckoutServiceProvider
        
        
    elendev.checkout.service_provider.paypal:
        class : GenCheckoutBundle\PaypalAPI\PaypalCheckoutService
        arguments : ["@service_container", "@router", %elendev.checkout.paypal.username%, %elendev.checkout.paypal.password%, %elendev.checkout.paypal.signature%, %elendev.checkout.paypal.use_sandbox%]
        tags : 
            - {name : elendev.checkout.service, id: paypal}